In [13]:
import torch


In [49]:

t = torch.ones(3, 1, requires_grad=True)
# t = t + 10
p = torch.ones(3, 1, requires_grad=True)
# p = p + 5
print(t)
print('t.grad:', t.grad)
print(p)
print('p.grad:', p.grad)
print()

y = 12*t #+ 3*p
print(y)

y.backward(t)
print('t.grad:', t.grad)
print('p.grad:', p.grad)
print()


tensor([[1.],
        [1.],
        [1.]], requires_grad=True)
t.grad: None
tensor([[1.],
        [1.],
        [1.]], requires_grad=True)
p.grad: None

tensor([[12.],
        [12.],
        [12.]], grad_fn=<MulBackward>)
t.grad: tensor([[12.],
        [12.],
        [12.]])
p.grad: None

